apiVersion: v1
kind: Service
metadata:
  name: {{.ServiceName}}
  namespace: {{.Namespace}}
spec:
  {{.TypeString}}
  ports:
    # the port that this service should serve on
  - name: http
    targetPort: my-http
    port: 8080
  - name: https
    targetPort: my-https
    port: 8443
  selector:
    firefly.selector: "{{.Selector}}"
